import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { deflateRawSync } from 'node:zlib';
import vm from 'node:vm';
import { createDocument, createPage, addNode, addEdge, parseDocument, assertDocument, removeItems } from '../src/core/model.js';
import { DocumentStore } from '../src/core/history.js';
import { pathGeometry, compoundGeometry, pathContours, svgPathData, flattenPath, validatePath } from '../src/core/drawing.js';
import { circleThrough, inkOutline } from '../src/core/curves.js';
import { booleanRegions, triangulateRegion, signedArea, regionContains } from '../src/core/regions.js';
import { layoutRichText, validateRichText, plainText } from '../src/core/rich-text.js';
import { validateImage, imagePlacement } from '../src/core/assets.js';
import { parseXML, xmlText, xmlAll } from '../src/core/xml.js';
import { readZIP, writeZIP, inflateRaw, archiveText } from '../src/core/archive.js';
import { exportNativePackage, importNativePackage, importLegacyXML } from '../src/core/native-diagram.js';
import { planTiles, tiledPrintHTML } from '../src/core/print.js';
import { CollaborationDocument } from '../src/core/collaboration.js';
const rect=(x,y,w,h)=>[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}],area=r=>Math.abs(r.reduce((sum,p)=>sum+signedArea(p),0)),near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} differs from ${b}`);
const scene=()=>{const d=createDocument('Advanced test'),p=d.pages[d.pageOrder[0]],id=addNode(d,p,'rectangle',100,100,{label:'Text'});return {d,p,id};};
const image={mime:'image/png',width:1,height:1,data:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQmcAAAAASUVORK5CYII=',alt:'Pixel'};
const triangulatedArea=tri=>{let sum=0;for(let i=0;i<tri.length;i+=3)sum+=Math.abs(signedArea(tri.slice(i,i+3)));return sum;};
test('booleans produce correct vector areas for overlapping, coincident, touching and disjoint operands',()=>{
  const a=[rect(0,0,100,100)],b=[rect(50,50,100,100)];for(const [op,expected]of [['union',17500],['intersection',2500],['difference',7500],['xor',15000]]){const r=booleanRegions(a,b,op);near(area(r),expected);near(triangulatedArea(triangulateRegion(r)),expected);}
  near(area(booleanRegions(a,a,'union')),10000);assert.deepEqual(booleanRegions(a,a,'difference'),[]);near(area(booleanRegions(a,[rect(100,0,100,100)])),20000);assert.equal(booleanRegions(a,[rect(300,0,20,20)]).length,2);
});
test('booleans preserve holes through normalized transforms and membership',()=>{
  const ring=booleanRegions([rect(-50,-50,200,200)],[rect(0,0,100,100)],'difference'),g=compoundGeometry(ring);assert.equal(g.contours.length,2);validatePath(g);assert.equal(regionContains({x:50,y:50},pathContours(g)),false);assert.equal(regionContains({x:-20,y:20},pathContours(g)),true);near(area(ring),30000);g.rotation=90;assert.equal(pathContours(g).length,2);assert.match(svgPathData(g),/ Z M/);
});
test('deterministic randomized rectangle booleans agree with analytic intersection area',()=>{
  let seed=7;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);for(let i=0;i<80;i++){const x=random()*100,y=random()*100,w=1+random()*70,h=1+random()*70,a=[rect(0,0,100,100)],b=[rect(x,y,w,h)],inter=Math.max(0,Math.min(100,x+w)-x)*Math.max(0,Math.min(100,y+h)-y);near(area(booleanRegions(a,b,'intersection')),inter,1e-4);near(area(booleanRegions(a,b,'union')),10000+w*h-inter,1e-4);}
});
test('scanline triangulation handles self-crossings and nonzero winding without translucent overlap',()=>{
  const bow=[[{x:0,y:0},{x:100,y:100},{x:0,y:100},{x:100,y:0}]];near(triangulatedArea(triangulateRegion(bow)),5000);const overlap=[rect(0,0,100,100),rect(50,0,100,100)];near(triangulatedArea(triangulateRegion(overlap,'evenodd')),10000);near(triangulatedArea(triangulateRegion(overlap,'nonzero')),15000);
});
test('three-point circular arc is analytic and survives ellipse transforms and native SVG arc output',()=>{
  const ps=[{x:0,y:0},{x:50,y:-50},{x:100,y:0}],c=circleThrough(...ps);near(c.x,50);near(c.y,0);near(c.r,50);near(Math.abs(c.sweep),Math.PI);const g=pathGeometry(ps,'circular');validatePath(g);assert.equal(g.path.length,3);assert.match(svgPathData(g),/ A50 50 /);g.h*=2;g.rotation=30;g.flipX=true;assert.match(svgPathData(g),/ A50 100 30 /);assert.ok(flattenPath(g).length>5);assert.throws(()=>circleThrough({x:0,y:0},{x:1,y:0},{x:2,y:0}),/non-collinear/);
});
test('pressure response changes actual ribbon width and retains editable centerline samples',()=>{
  const ps=[{x:0,y:0},{x:100,y:0}],low=inkOutline(ps,[.1,.1],10),high=inkOutline(ps,[1,1],10);assert.ok(area([high])>area([low])*3);assert.deepEqual(inkOutline(ps,[1,1],0),[]);const g={...pathGeometry(ps),pressures:[.1,1],tilts:[{x:0,y:30},{x:15,y:-15}],ink:{thinning:.9,gamma:2}};validatePath(g);assert.throws(()=>validatePath({...g,pressures:[2,1]}),/pressure/);assert.throws(()=>validatePath({...g,ink:{thinning:2,gamma:1}}),/response/);
});
test('rich text wraps complete codepoints and retains independent formatting runs, lists and alignment',()=>{
  const rich={version:1,paragraphs:[{align:'right',list:'number',runs:[{text:'Hello ',bold:true,size:20,color:'#ff0000'},{text:'world 😀😀',italic:true,underline:true,link:'https://example.org/'}]},{runs:[{text:'x'},{text:'2',script:'super'}]}]};validateRichText(rich);const layout=layoutRichText(rich,{x:0,y:0,w:90,h:200});assert.ok(layout.height>45);assert.ok(layout.runs.some(r=>r.bold));assert.ok(layout.runs.some(r=>r.link));assert.equal(plainText(rich),'Hello world 😀😀\nx2');assert.ok(!layout.runs.some(r=>/^[\ud800-\udbff]$/.test(r.text)));
});
test('rich text rejects active links, invalid marks and oversized layouts',()=>{for(const run of [{text:'x',link:'javascript:alert(1)'},{text:'x',link:'data:text/html,hi'},{text:'x',bold:1},{text:'x',color:'url(#bad)'},{text:'x',size:1000}])assert.throws(()=>validateRichText({version:1,paragraphs:[{runs:[run]}]}));});
test('embedded images are bounded data-only assets with non-destructive cropping',()=>{validateImage(image);assert.throws(()=>validateImage({...image,data:'https://example.org/pixel.png'}));assert.throws(()=>validateImage({...image,mime:'image/svg+xml'}));assert.throws(()=>validateImage({...image,width:9000}));assert.throws(()=>validateImage({...image,crop:{x:.8,y:0,w:.5,h:1}}));assert.deepEqual(imagePlacement({...image,width:200,height:100,fit:'contain'},{x:0,y:0,w:100,h:100}),{x:0,y:25,w:100,h:50,sx:0,sy:0,sw:200,sh:100});near(imagePlacement({...image,width:200,height:100,fit:'cover'},{x:0,y:0,w:100,h:100}).sw,100);});
test('rich content, exact arcs, pressure and compound geometry round-trip through native JSON and history',()=>{const {d,p,id}=scene();p.graph.nodes[id].richText={version:1,paragraphs:[{runs:[{text:'bold',bold:true}]}]};const arc=addNode(d,p,'path',0,0,{label:'',geometry:pathGeometry([{x:10,y:20},{x:20,y:10},{x:30,y:20}],'circular')});const asset=addNode(d,p,'image',10,10);p.graph.nodes[asset].image=image;const store=new DocumentStore(d);store.transact('region',()=>Object.assign(p.view.nodes[arc],compoundGeometry([rect(0,0,50,50),rect(10,10,10,10)])));store.undo();assert.equal(store.doc.pages[p.id].view.nodes[arc].pathMode,'circular');store.redo();assert.deepEqual(parseDocument(JSON.stringify(store.doc)),store.doc);});
test('inert XML rejects DTDs, unsafe entities, prototype attributes and malformed nesting',()=>{for(const source of ['<!DOCTYPE x [<!ENTITY a SYSTEM "file:///etc/passwd">]><x>&a;</x>','<a><b></a>','<x constructor="bad"/>','<x>&evil;</x>','<a/><b/>'])assert.throws(()=>parseXML(source));assert.equal(xmlText(parseXML('<a>A &amp; B <![CDATA[<x>]]>&#x1f600;</a>')),'A & B <x>😀');});
test('independent ZIP codec round-trips binary assets and checks CRC, traversal and size limits',()=>{const zipped=writeZIP(new Map([['hello.xml','<x>hello</x>'],['media/a.bin',new Uint8Array([0,1,2,255])]])),files=readZIP(zipped);assert.equal(archiveText(files.get('hello.xml')),'<x>hello</x>');assert.deepEqual([...files.get('media/a.bin')],[0,1,2,255]);const corrupt=zipped.slice();corrupt[40]^=1;assert.throws(()=>readZIP(corrupt));assert.throws(()=>writeZIP(new Map([['../escape','bad']])));});
test('raw DEFLATE decoder matches independent zlib stored/fixed/dynamic blocks',()=>{for(const size of [0,1,17,1000,100000])for(const level of [0,1,6,9]){const data=Buffer.from('A Bézier curve and image\n'.repeat(Math.ceil(size/20))).subarray(0,size),compressed=deflateRawSync(data,{level});assert.deepEqual(Buffer.from(inflateRaw(compressed,data.length)),data);if(size)assert.throws(()=>inflateRaw(compressed,data.length-1));}});
test('native package extension is lossless only while all standard parts remain unchanged',()=>{const {d}=scene(),packageBytes=exportNativePackage(d);assert.deepEqual(importNativePackage(packageBytes).doc,d);const files=readZIP(packageBytes);files.set('visio/pages/page1.xml',new TextEncoder().encode(archiveText(files.get('visio/pages/page1.xml')).replace('<Text>Text</Text>','<Text>Changed text</Text>')));const imported=importNativePackage(writeZIP(files));assert.ok(!imported.report.some(r=>r.code==='LOSSLESS_EXTENSION'));assert.ok(Object.values(imported.doc.pages[imported.doc.pageOrder[0]].graph.nodes).some(n=>n.label.includes('Changed text')));});
test('standard package parts independently import outlines, rich runs, media and glued connectors',()=>{
  const {d,p,id}=scene(),b=addNode(d,p,'ellipse',400,100,{label:'Target'});p.graph.nodes[id].richText={version:1,paragraphs:[{runs:[{text:'BOLD',bold:true,size:24}]}]};const im=addNode(d,p,'image',200,300);p.graph.nodes[im].image=image;const edge=addEdge(p,{nodeId:id,port:'auto'},{nodeId:b,port:'auto'},'connected',{waypoints:[{x:320,y:110},{x:330,y:180}]});
  const routes=new Map([[p.id,new Map([[edge,{points:[{x:245,y:130},{x:320,y:110},{x:330,y:180},{x:400,y:130}]}]])]]),files=readZIP(exportNativePackage(d,routes));files.delete('nexora/document.json');files.delete('nexora/manifest.json');const r=importNativePackage(writeZIP(files)),page=r.doc.pages[r.doc.pageOrder[0]];assert.equal(Object.keys(page.graph.nodes).length,3);assert.equal(Object.keys(page.graph.edges).length,1);assert.ok(Object.values(page.graph.nodes).some(n=>n.image));assert.ok(Object.values(page.graph.nodes).some(n=>n.richText?.paragraphs[0].runs[0].bold));assert.equal(Object.values(page.view.edges)[0].waypoints.length,2);assertDocument(r.doc);
});
test('foreign-generator legacy XML imports geometry, formulas, ellipse and polynomial spline rows',()=>{const r=importLegacyXML(readFileSync(new URL('./fixtures/external-generator.vdx',import.meta.url),'utf8')),p=r.doc.pages[r.doc.pageOrder[0]];assert.equal(Object.keys(p.graph.nodes).length,5);assert.ok(Object.values(p.graph.nodes).some(n=>n.label.includes('Receive')));assert.equal(r.report.filter(x=>x.severity==='warning').length,0);assert.ok(Object.values(p.view.nodes).some(g=>g.path.length>20));});
test('tiled print covers negative bounds with exact overlap and finite page budget',()=>{const box={x:-200,y:-100,w:1800,h:1400},plan=planTiles(box,{paper:'A4',margin:10,overlap:5,scale:1});assert.equal(plan.tiles[0].x,-200);const last=plan.tiles.at(-1);assert.ok(last.x+last.w>=1600);assert.ok(last.y+last.h>=1300);near(plan.tiles[0].w-(plan.tiles[1].x-plan.tiles[0].x),5*96/25.4);assert.equal(planTiles(box,{fit:true}).tiles.length,1);assert.throws(()=>planTiles(box,{margin:200}));assert.throws(()=>planTiles({x:0,y:0,w:1e6,h:1e6}));});
test('print output preserves native curves, assets, page labels and physical sheet dimensions',()=>{globalThis.document={createElement:()=>({getContext:()=>({font:'',measureText:text=>({width:[...text].length*8})})})};const {d,p}=scene();const asset=addNode(d,p,'image',200,100);p.graph.nodes[asset].image=image;const id=addNode(d,p,'path',0,0,{label:'',geometry:pathGeometry([{x:10,y:20},{x:20,y:10},{x:30,y:20}],'circular')});const html=tiledPrintHTML(d,[p],new Map(),{paper:'Letter'});assert.match(html,/@page\{size:215.9mm 279.4mm/);assert.match(html,/row 1/);assert.match(html,/ A10 10 /);assert.match(html,/data:image\/png;base64/);assert.ok((html.match(/class="sheet"/g)||[]).length>1);});
test('collaboration converges concurrent independent fields and deterministic same-record conflicts',()=>{const {d,p,id}=scene(),a=new CollaborationDocument(d,'peer_a'),b=new CollaborationDocument(d,'peer_b');const x=structuredClone(d),y=structuredClone(d);x.pages[p.id].view.nodes[id].x=600;y.pages[p.id].view.nodes[id].fill='#ff0000';const ma=a.local(x),mb=b.local(y);a.apply(mb);b.apply(ma);assert.deepEqual(a.last,b.last);assert.equal(a.last.pages[p.id].view.nodes[id].x,600);assert.equal(a.last.pages[p.id].view.nodes[id].fill,'#ff0000');const xa=structuredClone(a.last),yb=structuredClone(b.last);xa.pages[p.id].view.nodes[id].x=700;yb.pages[p.id].view.nodes[id].x=800;const m2a=a.local(xa),m2b=b.local(yb);a.apply(m2b);b.apply(m2a);assert.deepEqual(a.last,b.last);assert.equal(a.last.pages[p.id].view.nodes[id].x,800);assert.equal(a.apply(m2a).changed,false);});
test('collaboration tombstones defeat stale field updates without resurrecting deleted shapes',()=>{const {d,p,id}=scene(),a=new CollaborationDocument(d,'peer_a'),b=new CollaborationDocument(d,'peer_b'),x=structuredClone(d),y=structuredClone(d);removeItems(x.pages[p.id],[id]);y.pages[p.id].graph.nodes[id].label='stale update';const ma=a.local(x),mb=b.local(y);a.apply(mb);b.apply(ma);assert.deepEqual(a.last,b.last);assert.equal(a.last.pages[p.id].graph.nodes[id],undefined);const c=new CollaborationDocument(d,'peer_c');c.records=new Map();assert.deepEqual(c.apply(a.snapshot()).doc,a.last);});
test('collaboration retains shape creations delivered before their page and recovers deleted pages deterministically',()=>{
 const {d}=scene(),a=new CollaborationDocument(d,'peer_a'),b=new CollaborationDocument(d,'peer_b'),x=structuredClone(d),p=createPage('New page');x.pages[p.id]=p;x.pageOrder.push(p.id);const id=addNode(x,p,'rectangle',100,100);const m=a.local(x),node=m.changes.filter(c=>JSON.parse(c.key)[0]==='node'),other=m.changes.filter(c=>JSON.parse(c.key)[0]!=='node');b.apply({...m,changes:node});assert.ok(!b.last.pages[p.id]);b.apply({...m,changes:other});assert.deepEqual(a.last,b.last);assert.ok(b.last.pages[p.id].graph.nodes[id]);
 const gone={protocol:'nexora.sync.v1',type:'operation',stamp:[10,'peer_a'],changes:Object.keys(a.last.pages).map(id=>({key:JSON.stringify(['page',id]),field:'$alive',value:false}))};a.apply(gone);b.apply(gone);assert.deepEqual(a.last,b.last);assert.equal(a.last.pageOrder[0],'page_collaboration_recovery');
 const bogus={protocol:'nexora.sync.v1',type:'operation',stamp:[100,'peer_bad'],changes:[{key:'["node","page_x","__proto__"]',field:'x',value:1}]};assert.throws(()=>a.apply(bogus));assert.deepEqual(a.last,b.last);
});
test('collaboration rejects corrupt fields atomically and preserves valid document state',()=>{const {d,p,id}=scene(),a=new CollaborationDocument(d,'peer_a'),before=structuredClone(a.last);assert.throws(()=>a.apply({protocol:'nexora.sync.v1',type:'operation',stamp:[100,'peer_bad'],changes:[{key:JSON.stringify(['node',p.id,id]),field:'g:fill',value:'url(javascript:bad)'}]}));assert.deepEqual(a.last,before);assert.throws(()=>a.apply({protocol:'invalid'}));});
test('standalone bundle parses without expanding dollar replacement sequences',()=>{const html=readFileSync(new URL('../dist/Nexora-Diagram.html',import.meta.url),'utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);assert.equal((html.match(/<!doctype html>/gi)||[]).length>0,true);});
