import { addNode, isLocked, isVisible, removeItems } from '../core/model.js';
import { getMaster, shapeGeometry, isContainer } from '../core/stencils.js';
import { pathContours, compoundGeometry, pathGeometry } from '../core/drawing.js';
import { booleanRegions } from '../core/regions.js';
import { inkOutline } from '../core/curves.js';
import { imageFromFile, validateImage, cachedImage } from '../core/assets.js';
import { exportNativePackage, importNativePackage, importLegacyXML } from '../core/native-diagram.js';
import { PRINT_PAPERS, planTiles, tiledPrintHTML } from '../core/print.js';
import { exportScene } from '../core/export-svg.js';
import { RoutingService } from '../core/routing-service.js';
import { fitContainers } from '../core/layout.js';
import { editRichText } from './rich-editor.js';
import { CollaborationSession, invitationId } from './collaboration.js';
import { esc } from './icons.js';
const $=id=>document.getElementById(id);
const field=(id,label,value,type='number')=>`<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''}></label>`;
export function advancedRibbon(a){const b=(...args)=>a.ui.button(...args),g=(...args)=>a.ui.group(...args);return g('Rich content',b('rich-text','text','Rich text')+b('embed-image','open','Embed image')+b('image-properties','palette','Image crop'))+g('Vector operations',b('boolean-union','container','Union')+b('boolean-intersection','process','Intersect')+b('boolean-difference','layers','Subtract')+b('boolean-xor','decision','Exclude'))+g('Precision & ink',b('tool-circlearc','connector','Circular arc')+b('ink-settings','palette','Pressure ink')+b('edit-points','pointer','Edit points'))+g('Interchange & output',b('native-import','open','Import drawing')+b('native-export','save','Export package')+b('print-page','document','Tiled print'))+g('Live editing',b('collaborate','link',a.collaboration?'Session':'Collaborate'));}
function selectedNode(a){if(a.selection.size!==1)throw new Error('Select exactly one editable shape.');const id=[...a.selection][0],n=a.page.graph.nodes[id];if(!n||isLocked(a.page,id))throw new Error('Select an unlocked shape.');return n;}
export function booleanSelection(a,operation){
  const ids=[...a.selection].filter(id=>a.page.graph.nodes[id]&&isVisible(a.page,id)&&!isLocked(a.page,id));if(ids.length<2||ids.length!==a.selection.size)throw new Error('Select at least two unlocked closed shapes or pressure strokes.');
  const regions=ids.map(id=>{const n=a.page.graph.nodes[id],g=a.page.view.nodes[id];if(n.image||n.master==='text'||isContainer(a.doc,n))throw new Error('Ungroup containers and exclude images/text before combining outlines.');if(g.pressures&&!g.closed)return booleanRegions([inkOutline(shapeGeometry(getMaster(a.doc,n.master),g).points,g.pressures,g.strokeWidth||0,g.ink)],[],'union',{ruleA:'nonzero'});if(n.master==='path'){if(!g.closed)throw new Error('Close open paths before combining regions.');return pathContours(g);}return [shapeGeometry(getMaster(a.doc,n.master),g).points];});
  let rings=regions[0];for(let i=1;i<regions.length;i++)rings=booleanRegions(rings,regions[i],operation);
  const primary=ids[0];a.store.transact(`Region ${operation}`,()=>{
    if(!rings.length){removeItems(a.page,ids);return;}
    const n=a.page.graph.nodes[primary],g=a.page.view.nodes[primary],ports=n.ports||getMaster(a.doc,n.master).ports;
    if(ports?.length)n.ports=structuredClone(ports);else n.ports=[{id:'n',x:'w/2',y:0,dx:0,dy:-1},{id:'e',x:'w',y:'h/2',dx:1,dy:0},{id:'s',x:'w/2',y:'h',dx:0,dy:1},{id:'w',x:0,y:'h/2',dx:-1,dy:0}];
    n.master='path';Object.assign(g,compoundGeometry(rings));delete g.pressures;delete g.tilts;delete g.ink;g.z=a.page.view.nextZ++;
    // Preserve primary identity and redirect attached graph edges before deleting operands.
    for(const edge of Object.values(a.page.graph.edges))for(const end of ['from','to'])if(ids.includes(edge[end].nodeId))edge[end]={nodeId:primary,port:'auto'};
    removeItems(a.page,ids.slice(1));fitContainers(a.doc,a.page);
  });a.select(rings.length?[primary]:[]);a.setTool('pointer');return primary;
}
export async function addImage(a,file,at){
  const image=await imageFromFile(file),layer=a.page.layers.find(l=>l.id===a.activeLayer);if(!layer?.visible||layer.locked)throw new Error('Choose a visible unlocked layer.');
  const position=at||a.screenToWorld({x:a.camera.width/2,y:a.camera.height/2}),scale=Math.min(1,500/image.width,400/image.height);let id;
  a.store.transact('Embed image',()=>{id=addNode(a.doc,a.page,'image',position.x-image.width*scale/2,position.y-image.height*scale/2,{label:'',layerId:a.activeLayer,geometry:{w:Math.max(24,image.width*scale),h:Math.max(24,image.height*scale),fill:'none',stroke:'none',strokeWidth:0}});a.page.graph.nodes[id].image=image;});a.select([id]);return id;
}
function chooseFile(accept,callback,a){const input=document.createElement('input');input.type='file';input.accept=accept;input.hidden=true;input.dataset.advancedFile=accept;document.body.append(input);input.onchange=async()=>{try{if(input.files[0])await callback(input.files[0]);}catch(error){a.ui.showToast(error.message,true);}finally{input.remove();}};input.oncancel=()=>input.remove();input.click();}
function imageProperties(a){const n=selectedNode(a);if(!n.image)throw new Error('Select an embedded image.');const image=n.image,crop=image.crop||{x:0,y:0,w:1,h:1};
  a.ui.dialog('Embedded image & crop',`<img class="image-preview" alt="Image preview" src="${esc(image.data)}"><div class="property-grid">${field('image-alt','Description',image.alt||'','text')}<label class="field"><span>Fit</span><select id="image-fit">${['contain','cover','stretch'].map(v=>`<option${image.fit===v?' selected':''}>${v}</option>`).join('')}</select></label>${Object.entries(crop).map(([k,v])=>field(`image-${k}`,`Crop ${k} (%)`,+(v*100).toFixed(4))).join('')}</div><p>Crops are non-destructive. Original embedded pixels remain in the project. Drag the ordinary grips to resize or rotate the image.</p>`,()=>{const value=structuredClone(image);value.alt=$('image-alt').value;value.fit=$('image-fit').value;value.crop=Object.fromEntries(['x','y','w','h'].map(k=>[k,Number($(`image-${k}`).value)/100]));validateImage(value);a.store.transact('Crop image',()=>{a.page.graph.nodes[n.id].image=value;});});
}
function inkSettings(a){const g=a.page.view.nodes[[...a.selection][0]],settings=g?.ink||a.inkStyle||{thinning:.85,gamma:1};a.ui.dialog('Pressure-sensitive ink',`<div class="property-grid">${field('ink-thinning','Pressure influence (0–1)',settings.thinning)}${field('ink-gamma','Pressure response (0.1–4)',settings.gamma)}${field('ink-width','Nominal line width',g?.pressures?g.strokeWidth:a.drawStyle.strokeWidth)}</div><p>Pen pressure is recorded for every retained sample. Mouse and touch use a neutral pressure. Zero influence gives a constant-width stroke; higher influence follows pressure. Original samples, pressure and tilt metadata survive editing and saving.</p>`,()=>{
    const thinning=Number($('ink-thinning').value),gamma=Number($('ink-gamma').value),width=Number($('ink-width').value);if(!Number.isFinite(thinning)||thinning<0||thinning>1||!Number.isFinite(gamma)||gamma<.1||gamma>4||!Number.isFinite(width)||width<0||width>64)throw new Error('Use pressure influence 0–1, response 0.1–4 and width 0–64.');a.inkStyle={thinning,gamma};a.drawStyle.strokeWidth=width;
    const ids=[...a.selection].filter(id=>a.page.view.nodes[id]?.pressures&&!isLocked(a.page,id));if(ids.length)a.store.transact('Configure ink response',()=>{for(const id of ids){const g=a.page.view.nodes[id];g.ink={thinning,gamma};g.strokeWidth=width;}});else a.ui.renderInspector();
  });}
async function allRoutes(a,pages){const result=new Map();for(const p of pages){if(p.id===a.pageId){await a.routing.flush(a.doc,p);result.set(p.id,new Map(a.routing.routes));}else{const routing=new RoutingService();try{await routing.flush(a.doc,p);result.set(p.id,new Map(routing.routes));}finally{routing.dispose?.();routing.worker?.terminate();}}}return result;}
function downloadBlob(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export async function importDrawing(a,file){
  if(file.size>50*1024*1024)throw new Error('Drawing package exceeds 50 MB.');const bytes=new Uint8Array(await file.arrayBuffer());
  if(bytes[0]===0xd0&&bytes[1]===0xcf)throw new Error('This legacy binary container is not supported. Export an XML drawing package or XML interchange file from the source application.');
  const result=bytes[0]===0x50&&bytes[1]===0x4b?importNativePackage(bytes):importLegacyXML(new TextDecoder('utf-8',{fatal:true}).decode(bytes));
  // Decode embedded images before accepting the replacement document, not just their headers.
  for(const p of Object.values(result.doc.pages))for(const n of Object.values(p.graph.nodes))if(n.image){const entry=cachedImage(n.image);await entry.element.decode();if(entry.element.naturalWidth!==n.image.width||entry.element.naturalHeight!==n.image.height)throw new Error('Imported raster dimensions do not match its data.');entry.ready=true;}
  const count=Object.values(result.doc.pages).reduce((sum,p)=>sum+Object.keys(p.graph.nodes).length,0);a.ui.dialog('Import drawing — review conversion',`<p><strong>${result.doc.pageOrder.length} pages · ${count} shapes</strong></p><p>This replaces the current workspace. Download a project backup before importing. Executable formulas, macros and external relationships are never run.</p><div class="conversion-report">${result.report.length?result.report.map(r=>`<p class="${r.severity==='warning'?'import-warning':''}"><strong>${esc(r.code)}</strong>${r.object?` · ${esc(r.object)}`:''}<br>${esc(r.message)}</p>`).join(''):'<p>No conversion warnings were reported for the supported records.</p>'}</div><button type="button" id="import-report-download">Download conversion report</button>`,()=>{a.cancelInteraction?.();a.collaboration?.close();a.store.replace(result.doc);a.pageId=result.doc.pageOrder[0];a.selection.clear();a.clearIndex();a.ui.renderAll();a.fitPage();},'Replace workspace');$('import-report-download').onclick=()=>downloadBlob('Nexora-import-report.json',JSON.stringify(result.report,null,2),'application/json');return result;
}
export async function printSetup(a){
  a.ui.dialog('Tiled print & page layout',`<div class="property-grid"><label class="field"><span>Pages</span><select id="print-pages"><option value="current">Current page</option><option value="all">All document pages</option></select></label><label class="field"><span>Paper</span><select id="print-paper">${Object.keys(PRINT_PAPERS).map(p=>`<option>${p}</option>`).join('')}</select></label><label class="field"><span>Orientation</span><select id="print-orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label class="field"><span>Layout</span><select id="print-fit"><option value="tile">Tile at scale</option><option value="fit">Fit each drawing page to one sheet</option></select></label>${field('print-scale','Scale (%)',100)}${field('print-margin','Margin (mm)',10)}${field('print-overlap','Overlap (mm)',5)}</div><label class="ribbon-check"><input id="print-marks" type="checkbox" checked>Registration border and sheet labels</label><div class="print-controls"><button type="button" id="print-preview-button">Preview sheets</button><button type="button" id="print-html-button">Save printable HTML</button><span id="print-summary">Preview to calculate the sheet count.</span></div><iframe id="print-preview" title="Tiled print preview" class="print-preview" hidden></iframe><p>Physical scale uses 96 document pixels per inch. In the browser print dialog choose 100% scaling, the same paper/orientation, and disable browser headers/footers. Printer hardware margins remain device-dependent.</p>`,async()=>{const frame=await prepare();frame.contentWindow.focus();frame.contentWindow.print();},'Print');
  const prepare=async()=>{const pages=$('print-pages').value==='all'?a.doc.pageOrder.map(id=>a.doc.pages[id]):[a.page],routes=await allRoutes(a,pages),options={paper:$('print-paper').value,landscape:$('print-orientation').value==='landscape',margin:Number($('print-margin').value),overlap:Number($('print-overlap').value),scale:Number($('print-scale').value)/100,fit:$('print-fit').value==='fit',marks:$('print-marks').checked};
    const html=tiledPrintHTML(a.doc,pages,routes,options),count=pages.reduce((n,p)=>n+planTiles(exportScene(a.doc,p,routes.get(p.id)).box,options).tiles.length,0);$('print-summary').textContent=`${count} sheet${count===1?'':'s'}`;const frame=$('print-preview');frame.hidden=false;
    await new Promise(resolve=>{frame.onload=resolve;frame.srcdoc=html;});await Promise.all([...frame.contentDocument.querySelectorAll('image')].map(async node=>{const img=new Image();img.src=node.getAttribute('href')||node.getAttribute('xlink:href');await img.decode();}));frame.dataset.sheetCount=count;frame._nexoraHTML=html;return frame;};
  $('print-preview-button').onclick=()=>prepare().catch(error=>a.ui.showToast(error.message,true));$('print-html-button').onclick=async()=>{try{const frame=await prepare();downloadBlob('Nexora-print.html',frame._nexoraHTML,'text/html');}catch(error){a.ui.showToast(error.message,true);}};
}
function collaborationDialog(a){
  const session=a.collaboration;const room=session?.room||`room_${invitationId()}`;
  a.ui.dialog('Live collaboration',`<p>Peers in this browser origin can join by room ID. Remote peers exchange an offer and answer to establish an encrypted, reliable WebRTC data channel. No hosted relay or account is provided.</p><div class="property-grid">${field('session-name','Your display name',session?.name||'Editor','text')}${field('session-room','Room ID',room,'text')}</div><label class="field"><span>Optional ICE servers (JSON; contacted only when creating a remote connection)</span><textarea id="session-ice" rows="2" placeholder='[{"urls":"stun:your-server.example:3478"}]'>${esc(JSON.stringify(session?.iceServers||[]))}</textarea></label><div class="session-buttons"><button type="button" id="session-host">Start / resume session</button><button type="button" id="session-join">Join and replace workspace</button><button type="button" id="session-leave">Disconnect</button></div><p id="session-status">${session?`${session.ready?'Connected':'Waiting for host'} · ${session.peers.size} peers · ${session.channels.size} remote channels`:'Not connected. Save a backup before joining. Anyone with an invitation can edit.'}</p><hr><div class="session-buttons"><button type="button" id="session-offer">1. Create offer</button><button type="button" id="session-answer">2. Answer pasted offer</button><button type="button" id="session-accept">3. Accept pasted answer</button><button type="button" id="session-copy">Copy output</button></div><label class="field"><span>Paste the other peer’s offer or answer</span><textarea id="session-input" rows="3" spellcheck="false"></textarea></label><label class="field"><span>Your offer / answer to send to the other peer</span><textarea id="session-output" rows="3" readonly spellcheck="false"></textarea></label><p>Geometry and rich-text records resolve simultaneous same-record edits by deterministic last-writer order. Independent styles/data fields merge. Deletions remain tombstoned. Offline edits resynchronize on reconnection while this session remains open. Same-room transport snapshots are not an authorization boundary: share invitations only with trusted editors.</p>`,null,'Close');
  const status=message=>{$('session-status').textContent=message;},act=fn=>async()=>{try{await fn();}catch(error){status(error.message);a.ui.showToast(error.message,true);}};
  const start=join=>{const servers=JSON.parse($('session-ice').value||'[]');if(!Array.isArray(servers)||servers.length>10||servers.some(s=>!s||!(typeof s.urls==='string'||Array.isArray(s.urls))||[].concat(s.urls).some(u=>typeof u!=='string'||!/^turns?:|^stuns?:/.test(u))))throw new Error('ICE configuration must be an array of STUN/TURN server records.');a.cancelInteraction?.();a.collaboration?.close();a.collaboration=new CollaborationSession(a,{room:$('session-room').value,name:$('session-name').value,join,iceServers:servers});status(join?'Waiting for host. Current editing is paused until the shared document arrives.':'Session started. Share the room ID or exchange an offer and answer.');a.ui.renderRibbon();return a.collaboration;};
  $('session-host').onclick=act(()=>start(false));$('session-join').onclick=act(()=>start(true));$('session-leave').onclick=act(()=>{a.collaboration?.close();status('Disconnected; this document remains available locally.');a.ui.renderRibbon();});
  $('session-offer').onclick=act(async()=>{$('session-output').value=await (a.collaboration||start(false)).createOffer();status('Send this offer to the joining editor. Keep this session open.');});
  $('session-answer').onclick=act(async()=>{if(!a.collaboration)throw new Error('Join the offer’s room before answering. Joining replaces the workspace when connected.');$('session-output').value=await a.collaboration.answerOffer($('session-input').value);status('Send this answer back to the offer creator.');});
  $('session-accept').onclick=act(async()=>{if(!a.collaboration)throw new Error('Create an offer first.');await a.collaboration.acceptAnswer($('session-input').value);status('Answer accepted. Connection is negotiating; peer edits will appear when connected.');});
  $('session-copy').onclick=act(async()=>{await navigator.clipboard.writeText($('session-output').value);status('Copied invitation output.');});
}
export function installAdvanced(a){
  Object.assign(a.extraActions,{'rich-text':()=>editRichText(a),'embed-image':()=>chooseFile('image/png,image/jpeg,image/webp',file=>addImage(a,file),a),'image-properties':()=>imageProperties(a),'ink-settings':()=>inkSettings(a),'native-import':()=>chooseFile('.vsdx,.vdx,.xml',file=>importDrawing(a,file),a),'native-export':async()=>{const routes=await allRoutes(a,a.doc.pageOrder.map(id=>a.doc.pages[id]));downloadBlob('Nexora-drawing.vsdx',exportNativePackage(a.doc,routes),'application/vnd.ms-visio.drawing');},'print-page':()=>printSetup(a),collaborate:()=>collaborationDialog(a)});
  for(const operation of ['union','intersection','difference','xor'])a.extraActions[`boolean-${operation}`]=()=>booleanSelection(a,operation);
  const editLabel=a.editLabel;a.editLabel=(id)=>a.page.graph.nodes[id]?.richText?editRichText(a,id):editLabel(id);
  document.addEventListener('paste',e=>{if(e.target.closest('input,textarea,[contenteditable="true"],dialog'))return;const file=[...(e.clipboardData?.files||[])].find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();addImage(a,file).catch(error=>a.ui.showToast(error.message,true));}});
  const stage=$('stage');stage.addEventListener('dragover',e=>{if([...e.dataTransfer.items].some(i=>i.kind==='file'))e.preventDefault();});stage.addEventListener('drop',e=>{const file=[...e.dataTransfer.files].find(f=>f.type.startsWith('image/'));if(file){e.preventDefault();e.stopImmediatePropagation();const at=a.screenToWorld(a.pointerPosition(e));addImage(a,file,at).catch(error=>a.ui.showToast(error.message,true));}},true);
  window.addEventListener('pagehide',()=>a.collaboration?.close());
}
