import { advancedRibbon } from './advanced.js';
import { drawingRibbon, drawingInspector } from './drawing.js';
import { icon, esc } from './icons.js';
import { allMasters, getMaster, shapeGeometry, isContainer, getPorts, SAMPLE_MASTER } from '../core/stencils.js';
import { isVisible, isLocked, ancestors } from '../core/model.js';
import { resolveLabel } from '../core/expression.js';
const $ = id => document.getElementById(id);
const SWATCHES = ['#eaf3fc', '#e7f5ef', '#f1eafa', '#fff5df', '#ffefed', '#ffffff', '#dcebf7', '#d6ebe1', '#e3d6f1', '#fae8c0', '#f5d5d0', '#64748b'];
const colorField = (prop, value, label) => `<div class="field"><label>${label}</label><div class="color-field"><input type="color" data-prop="${prop}" value="${/^#[0-9a-f]{6}$/i.test(value || '') ? value : '#ffffff'}" aria-label="${label}"><span>${value === 'transparent' ? 'NONE' : esc(value || '')}</span></div></div>`;
const numberField = (prop, value, label, unit = 'px', min = '') => `<label class="field"><span>${label}</span><span class="input-with-unit"><input type="number" data-prop="${prop}" value="${Math.round(value * 100) / 100}" step="1" ${min !== '' ? `min="${min}"` : ''} aria-label="${label}"><span>${unit}</span></span></label>`;
export class Panels {
  constructor(app) { this.app = app; this.tab = 'Home'; this.leftTab = 'stencils'; this.inspectorTab = 'format'; this.expanded = new Set(['Basic flowchart', 'Basic shapes']); this.search = ''; this.dialogSubmit = null; }
  initialize() {
    $('quick-actions').innerHTML = this.ib('save-project', 'save', 'Download project (Ctrl+S)') + this.ib('undo', 'undo', 'Undo (Ctrl+Z)', 'undo-button') + this.ib('redo', 'redo', 'Redo (Ctrl+Shift+Z)', 'redo-button');
    $('custom-stencil-button').innerHTML = icon('plus', 17); $('search-icon').innerHTML = icon('search', 15); $('footer-spark').innerHTML = icon('spark'); $('breadcrumb-icon').innerHTML = icon('document'); $('fit-heading').innerHTML = icon('fit', 17); $('fit-status').innerHTML = icon('fit', 16); $('properties-icon').innerHTML = icon('layers', 17); $('export-button').innerHTML = icon('export', 13) + 'Export SVG';
    this.renderTabs(); this.renderRibbon(); this.renderStencils(); this.renderFloatingTools(); this.renderAll();
    $('dialog-form').addEventListener('submit', e => { e.preventDefault(); this.submitDialog(); });
  }
  ib(action, name, title, id = '') { return `<button ${id ? `id="${id}"` : ''} class="icon-button" data-action="${action}" title="${esc(title)}" aria-label="${esc(title)}">${icon(name, 17)}</button>`; }
  button(action, name, label, small = false, active = false, title = label) { return `<button class="tool-button${small ? ' small' : ''}${active ? ' active' : ''}" data-action="${action}" title="${esc(title)}">${icon(name, small ? 16 : 23)}<span>${esc(label)}</span></button>`; }
  group(label, content) { return `<div class="ribbon-group"><div class="ribbon-items">${content}</div><div class="group-label">${label}</div></div>`; }
  renderTabs() {
    $('ribbon-tabs').innerHTML = ['File', 'Home', 'Insert', 'Draw', 'Advanced', 'Design', 'Data', 'Process', 'View'].map(name => `<button data-ribbon-tab="${name}" class="ribbon-tab${this.tab === name ? ' active' : ''}${name === 'File' ? ' file' : ''}" role="tab" aria-selected="${this.tab === name}">${name}</button>`).join('') + `<div class="ribbon-tabs-right"><button class="help-link" data-action="help">${icon('help', 14)} Help & shortcuts</button></div>`;
  }
  renderRibbon() {
    const a = this.app, b = (...args) => this.button(...args), g = (...args) => this.group(...args);
    const tools = g('Tools', b('tool-pointer', 'pointer', 'Pointer', false, a.tool === 'pointer', 'Select and move (V)') + `<div class="ribbon-stack">${b('tool-connect', 'connector', 'Connector', true, a.tool === 'connect', 'Connect shapes (C)')}${b('add-text', 'text', 'Text', true, false, 'Add text (T)')}</div>`);
    const arrange = g('Arrange', `<div class="ribbon-stack"><select class="ribbon-select" data-command="align" aria-label="Align shapes"><option value="">⇥  Align shapes</option><option value="left">Align left</option><option value="center">Align centers</option><option value="right">Align right</option><option value="top">Align top</option><option value="middle">Align middles</option><option value="bottom">Align bottom</option></select><select class="ribbon-select" data-command="distribute" aria-label="Distribute shapes"><option value="">↔  Distribute</option><option value="x">Horizontally</option><option value="y">Vertically</option></select></div>` + b('auto-layout', 'layout', 'Auto layout', false, false, 'Cycle-aware layout with container and lock constraints'));
    const colors = g('Shape styles', `<div class="palette-ribbon">${SWATCHES.slice(0, 10).map(c => `<button class="swatch" data-fill="${c}" style="background:${c}" title="Fill ${c}" aria-label="Fill ${c}"></button>`).join('')}</div>`);
    const check = (key, label, value) => `<label class="ribbon-check"><input type="checkbox" data-setting="${key}" ${value ? 'checked' : ''}>${label}</label>`;
    let html;
    if (this.tab === 'Home') html = g('Clipboard', b('paste', 'paste', 'Paste') + `<div class="ribbon-stack">${b('copy', 'copy', 'Copy', true)}${b('duplicate', 'document', 'Duplicate', true)}</div>`) + tools + g('Quick shapes', b('add-process', 'process', 'Process') + b('add-decision', 'decision', 'Decision')) + arrange + colors + g('Select', b('select-all', 'pointer', 'Select all') + b('page-setup', 'document', 'Page setup'));
    else if (this.tab === 'Advanced') html = advancedRibbon(a);
    else if (this.tab === 'Draw') html = drawingRibbon(a);
    else if (this.tab === 'File') html = g('Document', b('new-document', 'document', 'New') + b('open-project', 'open', 'Open') + b('save-project', 'save', 'Save project')) + g('Export', b('export-svg', 'export', 'SVG vector') + b('export-png', 'export', 'PNG image') + b('export-selection', 'export', 'Selection SVG') + b('print-page', 'document', 'Print') + b('export-stencils', 'book', 'Stencils JSON')) + g('Examples', b('load-demo', 'layout', 'Approval flow') + b('download-sample-csv', 'data', 'Sample CSV'));
    else if (this.tab === 'Insert') html = g('Shapes', b('add-process', 'process', 'Process') + b('add-decision', 'decision', 'Decision') + b('add-text', 'text', 'Text')) + g('Rich content', b('rich-text','text','Rich text') + b('embed-image','open','Embed image')) + g('Structure', b('make-container', 'container', 'Container') + b('add-swimlane', 'lane', 'Swimlane')) + g('Reuse', b('custom-stencil', 'code', 'Programmable shape') + b('save-as-stencil', 'book', 'Save as stencil')) + g('Pages', b('add-page', 'plus', 'New page') + b('duplicate-page', 'copy', 'Duplicate page'));
    else if (this.tab === 'Design') html = arrange + colors + g('Constraints', `<div class="ribbon-stack">${check('maintainConstraints', 'Keep constraints', a.maintainConstraints)}${b('clear-constraints', 'unlock', 'Release constraints', true)}</div>`) + g('Group & transform', b('group', 'container', 'Group') + b('ungroup', 'container', 'Ungroup') + b('rotate-right', 'undo', 'Rotate 90°')) + g('Container', b('fit-containers', 'container', 'Fit to members') + b('bring-front', 'layers', 'Bring to front'));
    else if (this.tab === 'Data') html = g('External data', b('import-csv', 'data', 'Link CSV data') + b('download-sample-csv', 'document', 'Sample CSV')) + g('Properties', b('show-data', 'data', 'Shape data') + b('add-data-field', 'plus', 'Add field') + b('show-layers', 'layers', 'Layers')) + g('Labels', b('bind-label', 'link', 'Bind label') + b('validate', 'validate', 'Check bindings'));
    else if (this.tab === 'Process') html = g('Diagram validation', b('validate', 'validate', 'Check diagram') + b('reroute', 'connector', 'Reroute all')) + g('Structure', b('auto-layout', 'layout', 'Auto layout') + b('make-container', 'container', 'Container') + b('add-swimlane', 'lane', 'Swimlane')) + g('Constraints', b('clear-constraints', 'unlock', 'Release constraints') + b('clear-waypoints', 'connector', 'Reset connector'));
    else html = g('Zoom', b('fit', 'fit', 'Fit page') + b('zoom-selection', 'zoom', 'Selection') + b('zoom-100', 'zoom', '100%')) + g('Page', b('page-setup', 'document', 'Page setup') + b('fit-drawing', 'fit', 'Fit drawing')) + g('Canvas', `<div class="ribbon-stack">${check('grid', 'Show grid', a.grid)}${check('snap', 'Snap to grid', a.snap)}</div><div class="ribbon-stack">${check('guides', 'Smart guides', a.guides)}${check('minimap', 'Mini map', a.minimap)}</div>`) + g('Panels', b('show-layers', 'layers', 'Layers') + b('toggle-properties', 'palette', 'Properties') + b('show-outline', 'layout', 'Outline')) + g('Engine', b('engine-info', 'code', 'Diagnostics') + b('help', 'help', 'Shortcuts'));
    $('ribbon').innerHTML = html;
  }
  renderFloatingTools() {
    $('floating-tools').innerHTML = ['pointer', 'connect', 'hand'].map((tool, i) => `<button data-action="tool-${tool}" class="${this.app.tool === tool ? 'active' : ''}" title="${['Pointer (V)', 'Connector (C)', 'Pan (H)'][i]}" aria-label="${tool}">${icon(['pointer', 'connector', 'hand'][i], 18)}</button>`).join('') + '<div class="tool-separator"></div>' + this.ib('tool-line', 'connector', 'Draw line (L)') + this.ib('tool-pencil', 'code', 'Freehand (P)') + this.ib('add-text', 'text', 'Add text (T)');
  }
  renderStencils() {
    const masters = Object.values(allMasters(this.app.store.doc)).filter(m => !m.hidden), categories = [...new Set(masters.map(m => m.category))], search = this.search.toLowerCase();
    $('stencil-list').innerHTML = categories.map(category => {
      const items = masters.filter(m => m.category === category && (!search || `${m.name} ${category}`.toLowerCase().includes(search))); if (!items.length) return '';
      const expanded = this.expanded.has(category) || Boolean(search);
      return `<section class="stencil-category${expanded ? '' : ' collapsed'}"><button class="stencil-category-title" data-category="${esc(category)}">${icon('chevron', 12)}<span>${esc(category)}</span><span>${items.length}</span></button>${expanded ? `<div class="stencil-grid">${items.map(m => {
        const w = m.size[0], h = m.size[1], geo = shapeGeometry(m, { x: 0, y: 0, w, h }); const path = geo.points.map((p, i) => `${i ? 'L' : 'M'}${p.x} ${p.y}`).join(' ') + 'Z';
        return `<button class="stencil-shape" draggable="true" data-master="${esc(m.id)}" title="Drag or click to add ${esc(m.name)}"><svg viewBox="${-w * .09} ${-h * .12} ${w * 1.18} ${h * 1.24}" aria-hidden="true"><path d="${path}" fill="${m.geometry.kind === 'text' ? 'none' : '#f7f9fc'}" stroke="#9baec2" stroke-width="${Math.max(w, h) / 73}"/>${geo.details.map(ps => `<polyline points="${ps.map(p => `${p.x},${p.y}`).join(' ')}" fill="none" stroke="#9baec2" stroke-width="${w / 73}"/>`).join('')}${m.geometry.kind === 'text' ? `<text x="${w / 2}" y="${h * .8}" text-anchor="middle" font-family="Arial" font-size="${h}" fill="#9baec2">Text</text>` : ''}</svg><span>${esc(m.name)}</span></button>`;
      }).join('')}</div>` : ''}</section>`;
    }).join('') || '<p class="outline-empty">No matching stencils.</p>';
  }
  renderOutline() {
    const a = this.app, p = a.page, nodes = Object.values(p.graph.nodes), order = [];
    const children = new Map(); for (const n of nodes) { const key = n.parentId || null; if (!children.has(key)) children.set(key, []); children.get(key).push(n); }
    const stack = (children.get(null) || []).map(n => [n, 0]).reverse(); while (stack.length) { const [n, depth] = stack.pop(); order.push([n, depth]); const list = children.get(n.id) || []; for (let i = list.length - 1; i >= 0; i--) stack.push([list[i], depth + 1]); }
    $('outline-list').innerHTML = order.map(([n, depth]) => `<button data-select-node="${esc(n.id)}" class="outline-row${a.selection.has(n.id) ? ' selected' : ''}${isContainer(a.doc, n) ? ' container-row' : ''}" style="padding-left:${11 + Math.min(depth, 10) * 12}px;opacity:${isVisible(p, n.id) ? 1 : .4}" title="${esc(n.label)}">${icon(isContainer(a.doc, n) ? 'container' : n.master === 'decision' ? 'decision' : n.master === 'text' ? 'text' : 'process', 15)}<span>${esc(resolveLabel(n).split('\n')[0] || 'Untitled')}</span>${isLocked(p, n.id) ? icon('lock', 10) : ''}</button>`).join('') || '<p class="outline-empty">Your diagram hierarchy will appear here.</p>';
  }
  renderPages() {
    const a = this.app; $('page-tabs').innerHTML = a.doc.pageOrder.map(id => `<button data-page="${esc(id)}" class="page-tab${id === a.pageId ? ' active' : ''}" title="Double-click to rename page">${icon('document', 12)}${esc(a.doc.pages[id].name)}</button>`).join('');
    $('page-count').textContent = `Page ${a.doc.pageOrder.indexOf(a.pageId) + 1} of ${a.doc.pageOrder.length}`; $('page-heading').textContent = a.page.name;
  }
  renderInspector() {
    const a = this.app, p = a.page, ids = [...a.selection], n = ids.length === 1 ? p.graph.nodes[ids[0]] : null, e = ids.length === 1 ? p.graph.edges[ids[0]] : null;
    document.querySelectorAll('[data-inspector-tab]').forEach(b => b.classList.toggle('selected', b.dataset.inspectorTab === this.inspectorTab));
    $('inspector-title').textContent = this.inspectorTab === 'layers' ? 'Layers' : this.inspectorTab === 'data' ? 'Shape data' : 'Properties';
    if (this.inspectorTab === 'layers') return this.renderLayers();
    if (this.inspectorTab === 'data') return this.renderData(n || e);
    if (!n && !e && ids.length <= 1) return this.renderDocumentInspector();
    const g = n ? p.view.nodes[n.id] : e ? p.view.edges[e.id] : p.view.nodes[ids.find(id => p.view.nodes[id])];
    const title = n ? getMaster(a.doc, n.master).name : e ? 'Dynamic connector' : `${ids.length} selected objects`;
    let html = `<section class="property-section"><div class="shape-type"><span>${icon(e ? 'connector' : n?.master === 'decision' ? 'decision' : 'process')}</span><div><h3>${esc(title)}</h3><small>${n || e ? (isLocked(p, (n || e).id) ? 'Locked layer' : 'Selected · editable') : 'Multiple selection'}</small></div></div>`;
    if (n || e) html += `<label class="field"><span>Label</span><textarea data-label="true" aria-label="Shape label">${esc((n || e).label)}</textarea></label>${/\{\{/.test((n || e).label) ? `<p class="subtle-note">Preview: ${esc(resolveLabel(n || e))}</p>` : '<p class="subtle-note">Double-click a shape to edit on the canvas.</p>'}`;
    html += '</section>';
    if (n) {
      html += `<section class="property-section"><div class="section-title">Position & size ${icon('fit', 13)}</div><div class="property-grid">${numberField('x', g.x, 'X')}${numberField('y', g.y, 'Y')}${numberField('w', g.w, 'Width', 'px', 24)}${numberField('h', g.h, 'Height', 'px', 24)}</div><p class="subtle-note">Document coordinates · 96 units / inch</p></section>`;
    }
    if (g) {
      html += `<section class="property-section"><div class="section-title">${e ? 'Connector style' : 'Appearance'} ${icon('palette', 14)}</div><div class="property-grid">${!e ? colorField('fill', g.fill, 'Fill') : ''}${colorField('stroke', g.stroke, 'Line')}</div>${!e ? `<div class="property-swatches">${SWATCHES.slice(0, 10).map(c => `<button class="swatch" data-fill="${c}" style="background:${c}" title="${c}" aria-label="Fill ${c}"></button>`).join('')}</div>` : ''}<div class="property-row"><label>Line width</label><input type="number" data-prop="strokeWidth" value="${g.strokeWidth || 1.5}" min="0.5" max="12" step="0.5" aria-label="Line width"></div>${e ? `<div class="property-row checkbox"><label>Dashed line</label><input type="checkbox" data-prop="dashed" ${g.dashed ? 'checked' : ''}></div>` : `<div class="property-row"><label>Font size</label><input type="number" data-prop="fontSize" value="${g.fontSize || 16}" min="8" max="120" aria-label="Font size"></div><div class="property-grid">${colorField('textColor', g.textColor, 'Text color')}<label class="field"><span>Text alignment</span><select data-prop="align"><option value="left" ${g.align === 'left' ? 'selected' : ''}>Left</option><option value="center" ${!g.align || g.align === 'center' ? 'selected' : ''}>Center</option><option value="right" ${g.align === 'right' ? 'selected' : ''}>Right</option></select></label></div>`}</section>`;
    }
    if (n || e) {
      const obj = n || e; const memberships = n ? Object.values(p.graph.nodes).filter(x => isContainer(a.doc, x) && x.id !== n.id && !ancestors(p, x.id).includes(n.id)) : [];
      html += `<section class="property-section"><div class="section-title">Structure ${icon('layers', 14)}</div><div class="property-row"><label>Layer</label><select data-semantic="layerId">${p.layers.map(l => `<option value="${esc(l.id)}" ${obj.layerId === l.id ? 'selected' : ''}>${esc(l.name)}</option>`).join('')}</select></div>${n ? `<div class="property-row"><label>Container</label><select data-semantic="parentId"><option value="">None</option>${memberships.map(m => `<option value="${esc(m.id)}" ${n.parentId === m.id ? 'selected' : ''}>${esc(m.label)}</option>`).join('')}</select></div><div class="property-row"><label>Connections</label><span class="muted" style="font-size:11px">${getPorts(a.doc, n, g).length} points</span></div>` : `<p class="subtle-note">${esc(p.graph.nodes[e.from.nodeId]?.label.split('\n')[0])} → ${esc(p.graph.nodes[e.to.nodeId]?.label.split('\n')[0])}</p><p class="subtle-note">Double-click a line to add a waypoint. Drag endpoint handles to reconnect.</p><button class="full-button" data-action="clear-waypoints">${icon('connector')}Reset waypoints</button>`}<p class="subtle-note" title="${esc(obj.id)}">ID · ${esc(obj.id.slice(0, 20))}…</p></section>`;
      if (n) html += `<section class="property-section"><div class="section-title">Shape data <span>${Object.keys(n.data).length} fields</span></div><p>${esc(n.data.owner || 'Add structured properties to this shape.')} ${n.data.status ? `· ${esc(n.data.status)}` : ''}</p><button class="action-link" data-action="show-data">${icon('data')}View shape data</button></section>`;
    } else html += `<section class="property-section"><p>Use Arrange to align or distribute the selected shapes. Alignment constraints can remain active.</p></section>`;
    $('inspector-content').innerHTML = html + drawingInspector(a);
  }
  renderDocumentInspector() {
    const a = this.app, p = a.page, nodes = Object.values(p.graph.nodes), count = nodes.filter(n => !getMaster(a.doc, n.master).annotation && !isContainer(a.doc, n)).length;
    $('inspector-content').innerHTML = `<section class="property-section"><div class="section-title">Document</div><h3>${esc(a.doc.title)}</h3><p>A connected view of your process.</p><div class="document-preview"><svg viewBox="0 0 180 85" fill="none"><path d="M36 43h34m40 0h34M88 52v18h30" stroke="#bcb0ce" stroke-width="1.5"/><rect x="5" y="30" width="34" height="25" rx="12" fill="#e5f0ea" stroke="#afc8ba"/><rect x="70" y="29" width="39" height="27" rx="3" fill="#ede7f6" stroke="#bbaaCF"/><path d="m153 22 21 21-21 21-21-21Z" fill="#f9eed6" stroke="#dac896"/><rect x="118" y="61" width="33" height="17" rx="2" fill="#edf0f8" stroke="#bfc8dc"/></svg></div><div class="stat-grid"><div class="stat-card"><b>${count}</b><span>Shapes</span></div><div class="stat-card"><b>${Object.keys(p.graph.edges).length}</b><span>Connectors</span></div><div class="stat-card"><b>${nodes.filter(n => isContainer(a.doc, n)).length}</b><span>Containers</span></div><div class="stat-card"><b>${p.layers.length}</b><span>Layers</span></div></div></section><section class="property-section"><div class="section-title">Page setup ${icon('document')}</div><div class="property-grid">${numberField('pageWidth', p.width, 'Width')}${numberField('pageHeight', p.height, 'Height')}</div><button class="full-button" data-action="page-setup">${esc(p.canvasMode || 'fixed')} canvas · Page setup</button><button class="action-link" data-action="fit-content">Fit page to drawing</button><button class="action-link" data-action="page-left">Move page left</button><button class="action-link" data-action="page-right">Move page right</button><button class="action-link" data-action="rename-page">Rename this page</button><button class="action-link" data-action="duplicate-page">Duplicate page</button>${a.doc.pageOrder.length > 1 ? '<button class="action-link" data-action="delete-page">Delete page</button>' : ''}</section><section class="property-section"><div class="section-title">Your canvas, your flow</div><p>Select a shape to format it, edit its data, or inspect its connections.</p><div class="shortcut-row"><span>Pointer tool</span><kbd>V</kbd></div><div class="shortcut-row"><span>Connect shapes</span><kbd>C</kbd></div><div class="shortcut-row"><span>Fit diagram</span><kbd>F</kbd></div><div class="shortcut-row"><span>Undo</span><kbd>Ctrl Z</kbd></div><button class="full-button" data-action="validate">${icon('validate')}Validate diagram</button></section>` + drawingInspector(a);
  }
  renderData(node) {
    if (!node) { $('inspector-content').innerHTML = `<section class="property-section"><div class="section-title">Data-bound diagrams</div><h3>Select a shape</h3><p>Every shape can carry structured data. Use <code>{{owner}}</code> in a label to bind to a field.</p><button class="full-button" data-action="import-csv">${icon('data')}Link CSV data</button><button class="action-link" data-action="download-sample-csv">Download example CSV</button></section>`; return; }
    $('inspector-content').innerHTML = `<section class="property-section"><div class="section-title">${esc(getMaster(this.app.doc, node.master).name)} data ${icon('data')}</div><h3>${esc(resolveLabel(node).split('\n')[0])}</h3><p class="subtle-note">Use the “key” field for stable CSV matching.</p></section><section class="property-section"><div class="data-table">${Object.entries(node.data).map(([key, value]) => `<div class="data-entry"><label title="${esc(key)}">${esc(key)}</label><input data-data-key="${esc(key)}" value="${esc(typeof value === 'object' ? JSON.stringify(value) : value)}" aria-label="Data ${esc(key)}"><button data-delete-data="${esc(key)}" title="Remove ${esc(key)}">×</button></div>`).join('') || '<p>No fields yet.</p>'}</div><button class="action-link" data-action="add-data-field">${icon('plus')}Add data field</button></section><section class="property-section"><div class="section-title">Label binding</div><label class="field"><span>Label template</span><textarea data-label="true" aria-label="Label template">${esc(node.label)}</textarea></label><p class="subtle-note">Use <code>{{owner}}</code>, <code>{{status}}</code>, or any field name.</p><p class="subtle-note">Rendered: ${esc(resolveLabel(node))}</p><button class="full-button" data-action="import-csv">${icon('data')}Update from CSV</button></section>`;
  }
  renderLayers() {
    const a = this.app, p = a.page;
    $('inspector-content').innerHTML = `<section class="property-section"><div class="section-title">Page layers</div><p>Visibility and locking apply to members of containers as well. Click a layer name to make it active.</p></section>${p.layers.map(l => `<div class="layer-row${a.activeLayer === l.id ? ' active' : ''}"><button class="layer-name" data-active-layer="${esc(l.id)}">${icon('layers')}${esc(l.name)}</button><small>${[...Object.values(p.graph.nodes), ...Object.values(p.graph.edges)].filter(n => n.layerId === l.id).length}</small><button class="icon-button" data-layer-visible="${esc(l.id)}" title="${l.visible ? 'Hide' : 'Show'} layer">${icon(l.visible ? 'eye' : 'eyeoff')}</button><button class="icon-button" data-layer-lock="${esc(l.id)}" title="${l.locked ? 'Unlock' : 'Lock'} layer">${icon(l.locked ? 'lock' : 'unlock')}</button></div>`).join('')}<section class="property-section"><button class="full-button" data-action="add-layer">${icon('plus')}New layer</button><button class="action-link" data-action="rename-layer">Rename active layer</button><button class="action-link" data-action="delete-layer">Delete empty active layer</button></section>`;
  }
  renderAll() { $('document-title').textContent = this.app.doc.title; document.title = `${this.app.doc.title} — Nexora Diagram`; this.renderPages(); this.renderInspector(); if (this.leftTab === 'outline') this.renderOutline(); this.updateStatus(); }
  updateStatus() {
    const a = this.app, size = a.selection.size; $('selection-count').textContent = size ? `${size} object${size === 1 ? '' : 's'} selected` : 'No selection';
    $('zoom-label').textContent = `${+(a.camera.zoom * 100).toFixed(a.camera.zoom < .01 ? 2 : 0)}%`; $('zoom-slider').value = a.camera.zoom * 100;
    if ($('undo-button')) { $('undo-button').disabled = !a.store.undoStack.length; $('undo-button').title = `Undo ${a.store.undoStack.at(-1)?.label || ''} (Ctrl+Z)`; }
    if ($('redo-button')) { $('redo-button').disabled = !a.store.redoStack.length; $('redo-button').title = `Redo ${a.store.redoStack.at(-1)?.label || ''} (Ctrl+Shift+Z)`; }
  }
  setStatus(message) { $('status-message').textContent = message; }
  setSaved(message, error = false) { $('save-status').textContent = message; $('save-status').classList.toggle('error', error); }
  showToast(message, error = false) { clearTimeout(this.toastTimer); $('toast').textContent = message; $('toast').classList.toggle('error', error); $('toast').hidden = false; this.toastTimer = setTimeout(() => $('toast').hidden = true, error ? 7000 : 3500); }
  dialog(title, body, submit, confirm = 'Apply') {
    this.dialogSubmit = submit; $('dialog-title').textContent = title; $('dialog-body').innerHTML = body; $('dialog-footer').innerHTML = `<button type="button" data-action="close-dialog">${submit ? 'Cancel' : 'Close'}</button>${submit ? `<button type="submit" class="primary">${esc(confirm)}</button>` : ''}`;
    $('dialog').showModal(); $('dialog-body').querySelector('input,textarea,select')?.focus();
  }
  async submitDialog() { if (!this.dialogSubmit) { $('dialog').close(); return; } try { await this.dialogSubmit(); $('dialog').close(); this.dialogSubmit = null; } catch (error) { this.showToast(error.message, true); } }
  prompt(title, value, submit, label = 'Name') { this.dialog(title, `<label class="field"><span>${esc(label)}</span><input id="prompt-input" type="text" value="${esc(value)}" autocomplete="off"></label>`, () => { const text = $('prompt-input').value.trim(); if (!text) throw new Error('Enter a nonempty value.'); return submit(text); }); }
  showValidation(issues) {
    $('validation-panel').hidden = false; const errors = issues.filter(i => i.severity === 'error').length;
    $('validation-heading').textContent = issues.length ? `Diagram validation · ${errors} errors, ${issues.length - errors} warnings` : 'Diagram validation · All checks passed';
    $('validation-results').innerHTML = issues.length ? issues.map((i, n) => `<button class="validation-item ${i.severity}" data-issue="${n}">${icon(i.severity === 'error' ? 'close' : 'warning')}<code>${esc(i.code)}</code><span>${esc(i.message)}</span></button>`).join('') : `<div class="validation-good">${icon('check')}No structural or workflow issues found.</div>`;
  }
  help() {
    const shortcuts = [['Select / move', 'V'], ['Connector tool', 'C'], ['Add text', 'T'], ['Pan tool', 'H'], ['Temporary pan', 'Space'], ['Fit page', 'F'], ['Edit label', 'Enter'], ['Delete selection', 'Del'], ['Undo', 'Ctrl Z'], ['Redo', 'Ctrl Shift Z'], ['Copy / paste', 'Ctrl C / V'], ['Duplicate', 'Ctrl D'], ['Select all', 'Ctrl A'], ['Group / ungroup', 'Ctrl G / Ctrl Shift G'], ['Line / freehand', 'L / P'], ['Rectangle / ellipse', 'R / E'], ['Finish polyline', 'Enter'], ['Find shapes', 'Ctrl F'], ['Print', 'Ctrl P'], ['Save project', 'Ctrl S'], ['Nudge', 'Arrow keys'], ['Nudge 10 units', 'Shift Arrow']];
    this.dialog('A little less friction. A lot more flow.', `<p>Drag stencils onto the page. Select a shape to move or resize it. Use the Connector tool to drag between shape ports. Use Draw for lines, arrows, curves and freehand strokes.</p><div class="help-grid">${shortcuts.map(([name, key]) => `<div class="shortcut-row"><span>${name}</span><kbd>${key}</kbd></div>`).join('')}</div><p style="margin-top:17px">Double-click a shape to edit its label. Double-click a connector to add an editable routing waypoint. Shift-click to select multiple objects. Drag a selection from any member or empty space inside its bounds. Drag rightward for contained selection, leftward for crossing selection. Side grips resize one axis; Shift preserves proportions and Alt keeps the center fixed. Use Ctrl/Cmd + wheel to zoom and two-finger pinch on touch devices.</p><p>Projects stay in your browser. Download the JSON project for a portable backup. SVG exports retain vector shapes and editable text, not a screenshot.</p>`, null);
  }
}
